name: Update Activity Feed

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00运行
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: JasonEtco/activity-box@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit & Push
        run: |
          git config --global user.name "AirGHub"
          git config --global user.email "3026710475@qq.com"
          git add README.md
          git commit -m "Update activity log"
          git push
